# Generated by Django 2.2.12 on 2021-02-03 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=32)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('city', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Awaiting Delivery', 'Awaiting Delivery'), ('Currently On Route', 'Currently On Route'), ('Delivered', 'Delivered')], default='Awaiting Delivery', max_length=20)),
                ('description', models.CharField(default='', max_length=128)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Partner'),
        ),
    ]
