# Generated by Django 2.2.12 on 2021-02-04 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('area', models.CharField(choices=[('SOUTH', 'South'), ('CENTER', 'Center'), ('NORTH', 'North')], default='CENTER', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='rates',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.City'),
        ),
    ]
