# Generated by Django 2.2.12 on 2021-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagegroup',
            name='collection_date',
            field=models.DateField(),
        ),
    ]
