# Generated by Django 2.2.12 on 2021-02-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageGroup',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='group',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Awaiting Delivery', 'Awaiting Delivery'), ('Currently On Route', 'Currently On Route'), ('Delivered', 'Delivered')], default='Awaiting Delivery', max_length=20),
        ),
    ]
