# Generated by Django 2.2.12 on 2021-02-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(choices=[('SOUTH', 'Southern'), ('CENTER', 'Central'), ('NORTH', 'Northern')], default='CENTER', max_length=6),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Awaiting delivery', 'Awaiting delivery'), ('On route to destination', 'On route to destination'), ('Delivered', 'Delivered')], default='Awaiting delivery', max_length=20),
        ),
    ]
