# Generated by Django 2.2.12 on 2021-02-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='phone_number',
            field=models.CharField(max_length=32),
        ),
    ]
