# Generated by Django 2.2.12 on 2021-02-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20210202_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Awaiting Delivery'), ('ROUTE', 'Currently On Route'), ('DELIVERED', 'Delivered')], default='WAIT', max_length=5),
        ),
    ]
