# Generated by Django 2.2.12 on 2021-02-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20210204_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(choices=[('Central', 'Central'), ('Northern', 'Northern'), ('Southern', 'Southern')], max_length=16),
        ),
    ]
