# Generated by Django 2.2.12 on 2021-02-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(choices=[('NORTH', 'Northern'), ('CENTER', 'Central'), ('SOUTH', 'Southern')], default='CENTER', max_length=6),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(default='Missing', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
