# Generated by Django 2.2.12 on 2021-02-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
