# Generated by Django 2.2.12 on 2021-02-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Awaiting collection', 'Awaiting collection'), ('Warehoused', 'Warehoused'), ('On route to destination', 'On route to destination'), ('Delivered', 'Delivered')], default='Awaiting collection', max_length=32),
        ),
    ]
