# Generated by Django 2.2.12 on 2021-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20210204_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
