# Generated by Django 2.2.12 on 2021-02-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20210204_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(choices=[('Northern', 'Northern'), ('Central', 'Central'), ('Southern', 'Southern')], max_length=6),
        ),
        migrations.AlterField(
            model_name='package',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
