# Generated by Django 2.2.12 on 2021-02-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20210204_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(choices=[('Northern', 'Northern'), ('Central', 'Central'), ('Southern', 'Southern')], max_length=16),
        ),
    ]
