# Generated by Django 2.2.12 on 2021-02-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20210205_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Awaiting collection', 'Awaiting collection'), ('Received by the company', 'Received by the company'), ('On route to destination', 'On route to destination'), ('Delivered', 'Delivered')], default='Awaiting collection', max_length=32),
        ),
    ]
